### ISSUE TITLE
navbar is unresponsive

### ISSUE THREAD

**Issue by convoliution** [convoliution/convoliution.github.io#2]
I have a plan for it, but it'll take me a while before I have the free time to implement the solution

**Comment by convoliution** [comment]
The mi liu effect doesn't collapse fully when navigating to the about section on mobile.

This is likely due to the minimum media query being too large.

**Comment by convoliution** [comment]
Need new breakpoints for navbar:
- smaller minimum breakpoint for mobile
- small full navbar with 1rem padding
- medium+ full navbar with 4?rem padding

**Comment by convoliution** [comment]
Why do I even have a minimum breakpoint? Just make it the default.

**Comment by mykalu** [comment]
Done!

**Comment by convoliution** [comment]
Resolved with ad66edec2eb3609d86dd978108f1a175127cb376.
